// @ts-nocheck
"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function RoomModel(props) {
  const { nodes, materials } = useGLTF("/assets/models/room/room.glb");
  return (
    <group {...props} dispose={null}>
      <group position={[1.992, 1.455, 1.588]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_192.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_193.geometry}
          material={materials.Space_cat}
        />
      </group>
      <group position={[1.992, 1.482, 1.811]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_195.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_196.geometry}
          material={materials.Fisherman}
        />
      </group>
      <group position={[1.992, 1.646, 1.753]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_198.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_199.geometry}
          material={materials.ship_in_a_bottle}
        />
      </group>
      <group position={[1.992, 1.291, 1.423]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_201.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_202.geometry}
          material={materials.uncle_ottos_truck}
        />
      </group>
      <group position={[1.992, 1.52, 1.395]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_204.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_205.geometry}
          material={materials.girl_with_pearl_earring}
        />
      </group>
      <group position={[1.992, 1.648, 1.56]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_207.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_208.geometry}
          material={materials.Firewatch}
        />
      </group>
      <group position={[1.992, 1.233, 1.617]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_210.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_211.geometry}
          material={materials.death_from_below}
        />
      </group>
      <group position={[1.992, 1.29, 1.782]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_213.geometry}
          material={materials.bildreihe_wand_schwarz}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_214.geometry}
          material={materials.elephant_low_poly}
        />
      </group>
      <group position={[-1.315, -0.28, -0.723]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_155.geometry}
          material={materials.Stehlampe_iron}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_156.geometry}
          material={materials.Stehlampe_durchsichtig}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_158.geometry}
          material={materials.Glas_der_nachtischlampe}
          position={[0, 1.443, 0]}
        />
      </group>
      <group
        position={[2.001, -0.169, 2.216]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_4.geometry}
          material={materials.Schreibtischstuhl_stuhltop}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_5.geometry}
          material={materials.Bodenleiste}
        />
      </group>
      <group
        position={[-1.573, -0.179, 0.35]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_10.geometry}
          material={materials.Bodenleiste}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials.Schreibtischstuhl_stuhltop}
        />
      </group>
      <group
        position={[-0.147, -0.069, -2.27]}
        rotation={[Math.PI / 2, 0, Math.PI]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.Kissen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials["Bodenleiste.001"]}
        />
      </group>
      <group position={[-1.331, -0.147, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_55.geometry}
          material={materials.Gitterschranck_einfarbig_grau}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_56.geometry}
          material={materials.Gitterschranck_Boden}
        />
      </group>
      <group position={[-1.346, 0.173, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_58.geometry}
          material={materials.Gitterschranck_einfarbig_grau}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_59.geometry}
          material={materials.Gitterschranck_Boden}
        />
      </group>
      <group position={[-1.367, 0.538, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_61.geometry}
          material={materials.Gitterschranck_Boden}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_62.geometry}
          material={materials.Gitterschranck_einfarbig_grau}
        />
      </group>
      <group position={[-1.381, 0.822, 0.021]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_64.geometry}
          material={materials.Gitterschranck_einfarbig_grau}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.Gitterschranck_Boden}
        />
      </group>
      <group position={[0.109, -0.306, 0.047]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_101.geometry}
          material={materials.Wand}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_102.geometry}
          material={materials.Bodenleiste}
        />
      </group>
      <group position={[-1.338, -0.306, 1.62]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_118.geometry}
          material={materials.Schranck_wei}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_119.geometry}
          material={materials.schranck_drinnen}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_127.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[1.679, 0.997, 2.182]}
        rotation={[0, -0.401, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_164.geometry}
        material={materials.Schreibtischstuhl_stuhltop}
        position={[-1.315, -0.28, -0.723]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_99.geometry}
        material={materials.Kissen}
        position={[-0.31, 0.447, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_141.geometry}
        material={materials.Schreibtischstuhl_stuhltop}
        position={[1.718, 0.692, 2.198]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_190.geometry}
        material={materials.metal_tr}
        position={[-0.851, 0.667, -2.915]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_95.geometry}
        material={materials.Schranck_wei}
        position={[-0.31, 0.447, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_71.geometry}
        material={materials.Schranck_wei}
        position={[-0.305, 0.25, -1.812]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_73.geometry}
        material={materials.Schranck_wei}
        position={[-0.594, -0.042, -1.803]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_75.geometry}
        material={materials.Schranck_wei}
        position={[-0.015, -0.042, -1.804]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_77.geometry}
        material={materials.Schranck_wei}
        position={[-0.016, -0.042, -2.248]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_79.geometry}
        material={materials.Schranck_wei}
        position={[-0.594, -0.042, -2.253]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_81.geometry}
        material={materials.material_0}
        position={[-0.594, -0.288, -2.028]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_83.geometry}
        material={materials.Schranck_wei}
        position={[-0.015, -0.288, -2.028]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_85.geometry}
        material={materials.Schranck_wei}
        position={[-0.305, -0.139, -2.028]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_87.geometry}
        material={materials.metallgriff_nachtisch}
        position={[-0.305, 0.327, -1.783]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_143.geometry}
        material={materials.Schranck_wei}
        position={[1.594, 0.647, 1.773]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_145.geometry}
        material={materials.Schranck_wei}
        position={[1.594, 0.159, 1.232]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_147.geometry}
        material={materials.Schranck_wei}
        position={[1.594, 0.453, 2.317]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_149.geometry}
        material={materials.Schranck_wei}
        position={[1.349, 0.512, 1.778]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_151.geometry}
        material={materials.Schranck_wei}
        position={[1.947, 0.457, 1.776]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_153.geometry}
        material={materials["Material.004"]}
        position={[1.594, -0.007, 2.315]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_35.geometry}
        material={materials.Schranck_wei}
        position={[1.005, -0.077, -1.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_37.geometry}
        material={materials.Matratze}
        position={[1.005, 0.108, -1.036]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_41.geometry}
        material={materials.Kissen}
        position={[1.472, 0.317, -1.9]}
        rotation={[-0.006, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_43.geometry}
        material={materials.Kissen}
        position={[0.639, 0.36, -1.9]}
        rotation={[3.136, 0.072, -0.067]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_93.geometry}
        material={materials.Schranck_wei}
        position={[-0.31, 0.447, -2.107]}
        rotation={[0, -0.785, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_67.geometry}
        material={materials.Gitterschranck_einfarbig_grau}
        position={[-1.356, 0.34, 0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_186.geometry}
        material={materials.Bodenleiste}
        position={[-1.038, 0.645, -2.978]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_188.geometry}
        material={materials.metal_tr}
        position={[-0.697, 0.706, -2.939]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_139.geometry}
        material={materials.Schreibtischstuhl_stuhltop}
        position={[1.783, 0.697, 2.197]}
        rotation={[0, 0, -0.128]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_97.geometry}
        material={materials.Kissen}
        position={[-0.215, 0.343, -2.251]}
        rotation={[0, 0.722, -0.128]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7.geometry}
        material={materials.Bodenleiste}
        position={[2.004, -0.169, 2.217]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Bodenleiste}
        position={[-1.576, -0.179, 0.349]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_17.geometry}
        material={materials.Bodenleiste}
        position={[-0.147, -0.069, -2.273]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_69.geometry}
        material={materials.Schranck_wei}
        position={[-0.305, 0.25, -2.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_49.geometry}
        material={materials.Bettsttzen}
        position={[1.841, -0.231, -0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_51.geometry}
        material={materials.Bettsttzen}
        position={[0.177, -0.231, -2.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_53.geometry}
        material={materials.Bettsttzen}
        position={[1.841, -0.231, -2.052]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_125.geometry}
        material={materials.Golden_schreibtisch_head}
        position={[1.521, 1.288, 2.115]}
        rotation={[0, -0.401, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_129.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[1.615, 0.701, 2.155]}
        rotation={[0, -0.401, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_131.geometry}
        material={materials.Golden_schreibtisch_head}
        position={[1.582, 0.71, 2.14]}
        rotation={[0, -0.401, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_133.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[1.718, 0.692, 2.198]}
        rotation={[0, -0.401, -0.827]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_137.geometry}
        material={materials.Schreibtischlampe_lightbulb_strahler}
        position={[1.46, 1.187, 2.087]}
        rotation={[0.074, 0, -0.231]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_160.geometry}
        material={materials.Schreibtischlampe_lightbulb_strahler}
        position={[-1.317, 1.151, -0.723]}
        rotation={[-0.009, -0.091, -0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_168.geometry}
        material={materials.Stuhlsttzen}
        position={[0.865, 0.237, 1.59]}
        rotation={[-2.19, 1.339, 2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_170.geometry}
        material={materials.Stuhlsttzen}
        position={[0.655, 0.228, 1.619]}
        rotation={[2.19, 1.339, -2.203]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_172.geometry}
        material={materials.Stuhlsttzen}
        position={[0.902, 0.243, 1.864]}
        rotation={[-2.391, 1.308, 2.089]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_174.geometry}
        material={materials.Stuhlsttzen}
        position={[0.692, 0.233, 1.893]}
        rotation={[1.977, 1.376, -2.301]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_176.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[0.907, -0.025, 1.526]}
        rotation={[1.489, -0.54, -1.729]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_178.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[0.623, 0.025, 1.565]}
        rotation={[-1.456, -0.698, 1.749]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_180.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[0.955, -0.024, 1.879]}
        rotation={[1.198, -0.5, -1.719]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_182.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[0.669, 0.024, 1.903]}
        rotation={[-1.753, -0.738, 1.747]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_162.geometry}
        material={materials.Schreibtischstuhl_stuhltop}
        position={[-1.521, -0.291, -0.662]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_47.geometry}
        material={materials.Bettsttzen}
        position={[0.177, -0.231, -0.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_89.geometry}
        material={materials["Material.001"]}
        position={[-0.31, 0.583, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_112.geometry}
        material={materials.material_0}
        position={[-1.384, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_114.geometry}
        material={materials.material_0}
        position={[-1.338, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_116.geometry}
        material={materials.material_0}
        position={[-1.384, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_110.geometry}
        material={materials.material_0}
        position={[-1.338, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_108.geometry}
        material={materials.material_0}
        position={[-1.338, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_106.geometry}
        material={materials["Material.002"]}
        position={[-1.338, -0.306, 1.62]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_39.geometry}
        material={materials.Bettlaken}
        position={[1.036, 0.303, -1.08]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_45.geometry}
        material={materials.Kissen}
        position={[1.005, 0.427, -0.357]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_166.geometry}
        material={materials.Schreibtischstuhl_stuhltop}
        position={[0.595, 0.271, 1.769]}
        rotation={[-Math.PI, 1.435, -Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_104.geometry}
        material={materials.Boden}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_19.geometry}
        material={materials.BW_truck}
        position={[1.998, 1.646, 1.753]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_21.geometry}
        material={materials.BW_cat}
        position={[1.998, 1.454, 1.589]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_23.geometry}
        material={materials.BW_ship}
        position={[1.998, 1.29, 1.423]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_25.geometry}
        material={materials.bw_fisherman}
        position={[1.998, 1.482, 1.812]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_27.geometry}
        material={materials.SW_Firewatch}
        position={[1.998, 1.647, 1.56]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_29.geometry}
        material={materials.BW_girl}
        position={[1.998, 1.52, 1.394]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_31.geometry}
        material={materials.bw_death_from_below}
        position={[1.998, 1.234, 1.617]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_33.geometry}
        material={materials.Elephant_shcwarz_weis}
        position={[1.992, 1.291, 1.783]}
        rotation={[0, 0, Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_184.geometry}
        material={materials.Bodenleiste}
        position={[-1.027, 0.669, -3.002]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_91.geometry}
        material={materials.Glas_der_nachtischlampe}
        position={[-0.31, 0.463, -2.107]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_121.geometry}
        material={materials.schreibtischlampen_schwarz}
        position={[1.445, 1.116, 2.083]}
        rotation={[0, -0.401, -0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_123.geometry}
        material={materials.Golden_schreibtisch_head}
        position={[1.471, 1.229, 2.093]}
        rotation={[0, -0.401, -0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_135.geometry}
        material={materials.Glas_der_nachtischlampe}
        position={[1.455, 1.161, 2.086]}
      />
    </group>
  );
}

useGLTF.preload("/assets/models/room/room.glb");
